version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mydatabase
    restart: unless-stopped

  server:
    build: ./server
    container_name: server
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/myinventory
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    restart: unless-stopped

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mongo-data:
